name: data-air

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Run get air data code
        env:
          MONGO_USER_NAME: ${{ secrets.MONGO_USER_NAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          API_AIR_KEY: ${{ secrets.API_AIR_KEY }}
        run: python backend/trafficData/getAirData.py

